fixtures:
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "git://github.com/camptocamp/puppet-systemd.git"
  symlinks:
    redis_sentinel: "#{source_dir}"
