name          'Yelp/redis_sentinel'
version       '0.0.11'
source        'https://github.com/Yelp/puppet-redis_sentinel'
author        'Kyle Anderson <kyle@xkyle.com>'
license       'Apache License, Version 2.0'
summary       'Configure redis-sentinels'
description   'Configure redis-sentinels'
project_page  'https://github.com/Yelp/puppet-redis_sentinel'

dependency 'puppetlabs/concat'
dependency 'puppetlabs/stdlib'
dependency 'camptocamp/puppet-systemd'
